import java.awt.*;
import java.io.Serializable;


/**
 * NOTE: This class implements Serializable so that these types of objects can be converted into a byte stream
 * and saved onto disk.
 */
public class Panel implements Drawable, Serializable {
    private Task task;

    public Panel(Task task) {
        this.task = task;
    }

    public void movePanel(Lane lane) {

    }

    @Override
    public void draw(Graphics g) {

    }

    /**
     * NOTE: the equals method was generated by the IntelliJ IDE.
     * Compares this panel to the specified object. The result is true if and only if
     * the argument is not null, is a Panel instance, and the specified object represents this panel.
     *
     * @param o
     * @return
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Panel panel = (Panel) o;

        return task != null ? task.equals(panel.task) : panel.task == null;
    }

    /**
     * Gets the task associated with this panel.
     *
     * @return a Task.
     */
    public Task getTask() {
        return this.task;
    }

}
